In [38]:
import torch

# a = torch.tensor(range(16)).reshape(4, 4)
# b = torch.tensor(range(4))
# print(a)
# print(b)
# c = torch.einsum('ij,j->ij', a, b)
# print(c)

# aa = torch.ones(16).reshape(4,4)
# bb = torch.tensor(range(8)).reshape(4, 2).type('torch.FloatTensor')
# print(bb)
# print(torch.einsum('ij->ji', bb))
# print(torch.einsum('ij', bb))
# print(torch.einsum('ij,jk->ik', aa, bb))
# print(torch.einsum('ij,jk->k', aa, bb))

# a = torch.tensor(range(2)).type('torch.FloatTensor')
# b = torch.tensor(range(10, 12)).type('torch.FloatTensor')
# print(a, b)
# print(torch.einsum('i, i->', a, b))
# print(torch.einsum('i, j->i', a, b))
# print(torch.einsum('i, j->j', a, b))
# print(torch.einsum('i, j->ij', a, b))

a = torch.tensor(range(2)).type('torch.FloatTensor')
b = torch.tensor(range(10, 16)).reshape(2, 3).type('torch.FloatTensor')
print(a)
print(b)
print(torch.einsum('i, ij->', a, b))

tensor([0., 1.])
tensor([[10., 11., 12.],
        [13., 14., 15.]])
tensor(42.)


In [ ]:
import torch
A = torch.randn(16, 8, 5, 128, 128)
B = torch.randn(16, 8, 5, 128, 128)
print('A:', A.size())
print('B:', B.size())
print(A)
A = A.unsqueeze(3)
print(A)
B = B.unsqueeze(2)
print('Viewed A:', A.size())
print('Viewed B:', B.size())
C = torch.einsum('ijklno,ijlmno->ijkmno', A, B)
print('C:', C.size())

In [51]:
A = torch.tensor(range(6)).reshape(2, 3).type('torch.FloatTensor')
B = torch.ones(6).reshape(3,2)
print(A)
print(B)
print(torch.einsum('ij, jk->ik', A, B))


tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[ 3.,  3.],
        [12., 12.]])


In [56]:
"""
有两个tensor A和B，size都是[16, 8, 5, 128, 128]，想将两者的第2个维度，即size为5的维度，分别reshape为5x1和1x5的两个向量，然后计算外积，得到一个5x5的kernel。但是，在张量中进行这样的运算，同时保持其他维度不受影响，是比较困难的，而einsum可以完美就觉这种情况。
首先，A可以view成一个size为[18, 8, 5, 1, 128, 128]的tensor, 同理，B可以view为size为[16, 8, 1, 5, 128, 128]的tensor，此时，结果为可以表示为
"""

A = torch.tensor(range(6)).reshape(2, 3).type('torch.FloatTensor')
B = torch.tensor(range(6)).reshape(2, 3).type('torch.FloatTensor')
print(A)
print(B)
A = A.unsqueeze(1)
B = B.unsqueeze(0)
print(A.shape)
print(B.shape)
C = torch.einsum('ijk,jnk->ink', A, B)
print(C)
print(C.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
torch.Size([2, 1, 3])
torch.Size([1, 2, 3])
tensor([[[ 0.,  1.,  4.],
         [ 0.,  4., 10.]],

        [[ 0.,  4., 10.],
         [ 9., 16., 25.]]])
torch.Size([2, 2, 3])


In [57]:
A = torch.randn(2,2)
B = torch.tensor([10, 20])
C = A * B
print(A)
print(C)

tensor([[-0.3890, -0.8070],
        [ 1.6444,  0.3503]])
tensor([[ -3.8899, -16.1405],
        [ 16.4437,   7.0051]])
